WIP. Are getting some compilation errors that is solved by a clean. But there is something not ok with the derived formaters. Need to test some more:
[info] Compiling 1 Scala source to /Users/kristofer/sw/sp/spservices/exampleService/target/scala-2.11/classes...
[error] symbol value inst$macro$2#57604 does not exist in sp.example.APIExampleService$$anonfun$writeReq$1.apply, which contains locals .
[error] Method code: final def apply(): julienrf#41.json#35012.derived#35014.DerivedOWrites#35021 = inst$macro$2
[trace] Stack trace suppressed: run last exampleService/compile:compileIncremental for the full output.
[error] (exampleService/compile:compileIncremental) scala.reflect.internal.FatalError: symbol value inst$macro$2#57604 does not exist in sp.example.APIExampleService$$anonfun$writeReq$1.apply, which contains locals .
[error] Method code: final def apply(): julienrf#41.json#35012.derived#35014.DerivedOWrites#35021 = inst$macro$2
[error] Total time: 3 s, completed 2017-aug-03 17:43:53